/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CourseTransformer from '#transformers/course_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Course = InferData<CourseTransformer>
  export namespace Course {
    export type Variants = InferVariants<CourseTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
