/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Courses: () => import('#controllers/courses_controller'),
  Grades: () => import('#controllers/grades_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Session: () => import('#controllers/session_controller'),
  Students: () => import('#controllers/students_controller'),
  SubjectPrerequisites: () => import('#controllers/subject_prerequisites_controller'),
  SubjectReservations: () => import('#controllers/subject_reservations_controller'),
  Subjects: () => import('#controllers/subjects_controller'),
  Users: () => import('#controllers/users_controller'),
}
